# .github/workflows/caller-workflow.yml
name: File Call Reusable Workflow

on:
  workflow_dispatch

jobs:
  call-reusable-workflow:
    uses: testforgha/reusable-workflow/.github/workflows/reusable-workflow-2.yml@feature-file
