# .github/workflows/caller-workflow.yml
name: Call Reusable Workflow

on:
  workflow_dispatch

jobs:
  call-reusable-workflow:
    uses: testforgha/reusable-workflow/.github/workflows/reusable-flow.yml@feature/test
